name: Disparadores (triggers)
run-name : "Aprendiendo a utilizar triggers"

on:
  workflow_dispatch:
    inputs:
      lenguaje_favorito:
        description: '¿Cuál es tu lenguaje de programación favorito?'
        required: true
        type: choice
        options:
          - JavaScript
          - Python
          - Java
      nombre:
        description: '¿Cuál es tu nombre?'
        required: true
        type: string
  schedule:
    - cron: '0 9 * * 1'  # Cada lunes a las 9 AM UTC
  push:
    branches:
        - develop
  issues:
    types: [opened, deleted]

jobs:
  hola-mundo-manual:
    runs-on: ubuntu-latest

    steps:
      - name: Saludo personalizado
        run: echo "Hola, ${{ github.event.inputs.nombre || 'Desconocido' }}! Veo que tu lenguaje favorito es ${{ github.event.inputs.lenguaje_favorito }}."
  hola-mundo:
    if: github.event_name == 'schedule' || github.event_name == 'push' || github.event.action == 'opened' || github.event.action == 'deleted'
    runs-on: ubuntu-latest
    steps:
      - name: Saludo genérico
        run: echo "Hola, este es un saludo automático disparado por el evento ${{ github.event_name }}."